on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
    - name: Setup dependencies
      run: |
        uv sync --group dev
    - name: Build executable
      run: uv run pyinstaller --onefile --name clincnv2vcf_${{ matrix.os }} clincnv2vcf.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clincnv2vcf-${{ matrix.os }}
        path: dist/*
